name: DAST - Testes Dinâmicos de Segurança (OWASP ZAP)

on:
  push:
  pull_request:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  dast:
    name: Rodar DAST com OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Rodar OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "https://www.momentodev.com/"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}