name: Teste E2E

on:
  workflow_call:
    inputs:
      branch:
        description: "Testes E2E"
        required: false
        type: string
        default: "main"
    secrets:
      CYPRESS_PROJECT_ID: { required: false }

jobs:
  test:
    name: ğŸ§ª Testes com Cypress
    runs-on: ubuntu-latest
   
    steps:
      - name: ğŸš€ Checkout do RepositÃ³rio
        uses: actions/checkout@v4

      - name: ğŸ“¦ Instalar dependÃªncias
        run: npm ci

      - name: ğŸ§ª Rodar testes do Cypress
        env: 
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        uses: cypress-io/github-action@v6
        with:
          record: true
          spec: "cypress/e2e/**/*.cy.js"

      - name: ğŸ—ƒï¸ Salvar evidÃªncias dos testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ğŸ“‘ EvidÃªncias dos Testes
          path: cypress/reports