name: Testar e Publicar no GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  teste-e-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
       # 1. Passo a passo para rodar os testes
      - name: ğŸš€ Checkout do RepositÃ³rio
        uses: actions/checkout@v4

      # 2. Instalando npm
      - name: ğŸ“¦ Instalar dependÃªncias do projeto
        run: npm install --only=dev

       # 4. Roda os testes por fim
      - name: ğŸ§ª Rodando os testes do Cypress
        continue-on-error: true
        uses: cypress-io/github-action@v6
        with:
          spec: "cypress/e2e/**/*.cy.js"
        if: always()
      - uses: actions/upload-artifact@v4
        with:
          name: ğŸ“‘ EvidÃªncias dos Testes
          path: cypress/reports

      - name: âš™ï¸ Configurar GitHub Pages
        uses: actions/configure-pages@v5
      - name: ğŸ“¦ Upload dos Artefatos do Projeto
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: ğŸ› ï¸ Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4