name: Teste Jest

on:
  workflow_call:
    inputs:
      branch:
        description: "Testes Jest"
        required: false
        type: string
        default: "main"

jobs:
  test:
    name: ğŸ§ª Testes com Jest
    runs-on: ubuntu-latest
   
    steps:
      - name: ğŸš€ Checkout do RepositÃ³rio
        uses: actions/checkout@v4

      - name: ğŸ“¦ Instalar dependÃªncias
        run: npm ci

      - name: ğŸ§ª Rodar os testes do Jest
        run: npm test

      - name: ğŸ“‚ Upload das evidÃªncias de teste
        uses: actions/upload-artifact@v4
        with:
          name: ğŸ“‘ EvidÃªncias dos Testes
          path: relatorio.html